baseURL = "https://www.travelexperiencias.com"
languageCode = "es"
title = "Travel Experiencias"
Paginate = 1000
googleAnalytics = ""
theme = "showcase"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

[params]
  author = "Travel Experiencias"
  description = "Minimal, one page, theme for showcasing your work"
  message = ""
  hideAutoMenu = true

[[menu.main]]
  name = "External"
  url = "https://example.com"

[social]
  facebook = "https://facebook.com"
  instagram = "https://instagram.com"
